name = "Functional"
uuid = "ce970980-c85a-4e0f-a4e1-5e83bdb1d947"
authors = ["Manuele Lucchi <manuele.lucchi@studenti.unimi.it>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
